### ISSUE TITLE
1cfg -h or 1cfg --help should give zero exit status

### ISSUE THREAD

**Issue by alzadude** [BrunoBonacci/1config#32]
Hi there,

I'm writing some scripts that need to check if various cli tools are installed correctly, typically for this I check the exit status is `0` after running `sometool -h`, `sometool --help`, `sometool -v`, `sometool --version` etc.

I need to make this check for 1config, but currently `1cfg -h` or `1cfg --help` exits with `1` so I can't do it.

Would you be able to make `1cfg -h` give exit status `0`?

Thanks 🙂

**Comment by BrunoBonacci** [comment]
That's a good idea! I will add this to next version.
out of curiosity which version are you currently using?

**Comment by BrunoBonacci** [comment]
released in `v0.21.0`

**Comment by alzadude** [comment]
> That's a good idea! I will add this to next version.
> out of curiosity which version are you currently using?

Hi @BrunoBonacci I'm currently using 0.16.4 but I can see you've implemented this now in a new version, I'll update my script to use that instead. Thanks 🙂
