### ISSUE TITLE
[UI] grid alignment

### ISSUE THREAD

**Issue by BrunoBonacci** [BrunoBonacci/1config#8]
For the following fields it is more desireable a centred alignment of the values in the table:

  - Environment
  - Version
  - change num
  - type
  - type
  - Value

possibly type and value have smaller width cells.

**Comment by etolbakov** [comment]
@BrunoBonacci wdyt about the following layout? I guess there will be more columns in the future (at least a column with checkboxes for comparing 2 config versions).
Or there is another option - shrink all columns and place statically the "New Entry" menu on the left side(currently it slides back and forth)
<img width="1678" alt="Screenshot 2019-12-25 at 18 09 20" src="https://user-images.githubusercontent.com/3762201/71449367-bbc81c00-2742-11ea-8789-d15b60d0928b.png">

**Comment by BrunoBonacci** [comment]
I think it looks ok! It might solve a small issue with Firefox as well.
With Firefox the service name is partially clipped

see picture:
![image](https://user-images.githubusercontent.com/1639862/71449810-35fd9e00-274d-11ea-8110-2951315e6b18.png)

**Comment by BrunoBonacci** [comment]
Fixed with https://github.com/BrunoBonacci/1config/pull/14
