### ISSUE TITLE
[UI] "Key" field not visible when many entries with the same key are present

### ISSUE THREAD

**Issue by BrunoBonacci** [BrunoBonacci/1config#9]
If there are loads of entries with the same key, the key won't be visible

![image](https://user-images.githubusercontent.com/1639862/71325631-778d0f80-24e7-11ea-9222-272a5fce4469.png)

either we need to repeat the key on every entry or make it "sticky" (non-scrollable)

**Comment by etolbakov** [comment]
I guess it's not relevant anymore

**Comment by BrunoBonacci** [comment]
correct, fixed with PR #23
